"use client";

import { useEffect, useState } from "react";

type WatchRow = {
  ticker: string;
  lastClose: number;
  cumulativeReturn: number;
  maxDrawdown: number;
  annualizedVolatility: number;
  asOf: string;
};

type WatchlistData = {
  watchlist: WatchRow[];
  generatedAt: string;
  tickers: string[];
};

function pct(x: number) {
  return `${(x * 100).toFixed(2)}%`;
}

export default function Home() {
  const [data, setData] = useState<WatchlistData | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch("/data/watchlist.json")
      .then((r) => {
        if (!r.ok) throw new Error(`Failed to load watchlist.json (${r.status})`);
        return r.json();
      })
      .then(setData)
      .catch((e) => setError(String(e)));
  }, []);

  return (
    <main style={{ padding: 24, fontFamily: "system-ui" }}>
      <h1 style={{ fontSize: 32, marginBottom: 8 }}>
        Equity Research Agent + Portfolio Monitor
      </h1>
      <p style={{ maxWidth: 760 }}>
        Watchlist analytics generated by a Python pipeline (returns, drawdown, volatility).
        Data lives in <code>public/data</code> and is rendered by this Next.js app.
      </p>

      <div style={{ marginTop: 18 }}>
        {!data && !error && <p>Loading watchlist…</p>}
        {error && <p style={{ color: "red" }}>Error: {error}</p>}

        {data && (
          <>
            <p style={{ opacity: 0.75 }}>
              Generated at: {new Date(data.generatedAt).toLocaleString()}
            </p>

            <table
              style={{
                marginTop: 12,
                borderCollapse: "collapse",
                width: "100%",
                maxWidth: 900,
              }}
            >
              <thead>
                <tr>
                  {["Ticker", "Last Close", "1Y Return", "Max Drawdown", "Ann. Vol"].map(
                    (h) => (
                      <th
                        key={h}
                        style={{
                          textAlign: "left",
                          borderBottom: "1px solid #ddd",
                          padding: "10px 8px",
                        }}
                      >
                        {h}
                      </th>
                    )
                  )}
                </tr>
              </thead>
              <tbody>
                {data.watchlist.map((row) => (
                  <tr key={row.ticker}>
                    <td style={{ padding: "10px 8px" }}>
                      <a href={`/ticker/${row.ticker}`} style={{ textDecoration: "underline" }}>
                        {row.ticker}
                      </a>
                    </td>
                    <td style={{ padding: "10px 8px" }}>{row.lastClose.toFixed(2)}</td>
                    <td style={{ padding: "10px 8px" }}>{pct(row.cumulativeReturn)}</td>
                    <td style={{ padding: "10px 8px" }}>{pct(row.maxDrawdown)}</td>
                    <td style={{ padding: "10px 8px" }}>{pct(row.annualizedVolatility)}</td>
                  </tr>
                ))}
              </tbody>
            </table>

            <p style={{ marginTop: 18, opacity: 0.8 }}>
              Click a ticker to open a research page (we’ll build that tomorrow).
            </p>
          </>
        )}
      </div>
    </main>
  );
}
