"use client";

import { useEffect, useState } from "react";

type WatchRow = {
  ticker: string;
  lastClose: number;
  cumulativeReturn: number;
  maxDrawdown: number;
  annualizedVolatility: number;
  asOf: string;
};

type WatchlistData = {
  watchlist: WatchRow[];
  generatedAt: string;
  tickers: string[];
};

function pct(x: number) {
  return `${(x * 100).toFixed(2)}%`;
}

function ReturnCell({ value }: { value: number }) {
  const formatted = pct(value);
  const colour =
    value > 0
      ? "text-emerald-600 dark:text-emerald-400"
      : value < 0
      ? "text-red-500 dark:text-red-400"
      : "text-slate-500";
  return <span className={colour}>{formatted}</span>;
}

export default function Home() {
  const [data, setData] = useState<WatchlistData | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch("/data/watchlist.json")
      .then((r) => {
        if (!r.ok) throw new Error(`Failed to load watchlist.json (${r.status})`);
        return r.json();
      })
      .then(setData)
      .catch((e) => setError(String(e)));
  }, []);

  return (
    <main className="mx-auto max-w-4xl p-6 font-sans">
      <h1 className="mb-2 text-3xl font-bold tracking-tight">
        Equity Research Agent
      </h1>
      <p className="mb-6 max-w-2xl text-slate-600 dark:text-slate-400">
        Watchlist analytics generated by a Python pipeline — returns, drawdown,
        and volatility. Click a ticker for the full research pack.
      </p>

      {!data && !error && (
        <p className="text-slate-500">Loading watchlist…</p>
      )}
      {error && (
        <p className="text-red-500">Error: {error}</p>
      )}

      {data && (
        <>
          <p className="mb-3 text-xs text-slate-400">
            Generated at: {new Date(data.generatedAt).toLocaleString()}
          </p>

          <div className="overflow-x-auto">
            <table className="w-full border-collapse text-sm">
              <thead>
                <tr className="border-b border-slate-200 dark:border-slate-700">
                  {["Ticker", "Last Close", "1Y Return", "Max Drawdown", "Ann. Vol"].map(
                    (h) => (
                      <th
                        key={h}
                        className="px-3 py-2.5 text-left font-medium text-slate-500 dark:text-slate-400"
                      >
                        {h}
                      </th>
                    )
                  )}
                </tr>
              </thead>
              <tbody>
                {data.watchlist.map((row) => (
                  <tr
                    key={row.ticker}
                    className="border-b border-slate-100 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800/50"
                  >
                    <td className="px-3 py-2.5">
                      <a
                        href={`/ticker/${row.ticker}`}
                        className="font-mono font-semibold text-indigo-600 hover:underline dark:text-indigo-400"
                      >
                        {row.ticker}
                      </a>
                    </td>
                    <td className="px-3 py-2.5 tabular-nums">
                      ${row.lastClose.toFixed(2)}
                    </td>
                    <td className="px-3 py-2.5 tabular-nums">
                      <ReturnCell value={row.cumulativeReturn} />
                    </td>
                    <td className="px-3 py-2.5 tabular-nums">
                      <ReturnCell value={row.maxDrawdown} />
                    </td>
                    <td className="px-3 py-2.5 tabular-nums">
                      {pct(row.annualizedVolatility)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}
    </main>
  );
}
