"use client";

import { useEffect, useState, KeyboardEvent } from "react";
import { useRouter } from "next/navigation";
import CorrelationHeatmap from "./CorrelationHeatmap";

type WatchRow = {
  ticker: string;
  lastClose: number;
  cumulativeReturn: number;
  maxDrawdown: number;
  annualizedVolatility: number;
  asOf: string;
};

type WatchlistData = {
  watchlist: WatchRow[];
  generatedAt: string;
  tickers: string[];
  correlationMatrix?: {
    tickers: string[];
    values: number[][];
  };
};

// ── Debounce hook ────────────────────────────────────────────────────────────
// Returns a copy of `value` that only updates after `delay` ms of no changes.
// Useful when you want to wait for the user to stop typing before doing
// something expensive (an API call, a search, etc.).
function useDebounce<T>(value: T, delay: number): T {
  const [debounced, setDebounced] = useState<T>(value);
  useEffect(() => {
    const id = setTimeout(() => setDebounced(value), delay);
    // The cleanup function runs before the next effect — it cancels the timer
    // so a new one can start.  Without this, every keystroke would fire.
    return () => clearTimeout(id);
  }, [value, delay]);
  return debounced;
}

function pct(x: number) {
  return `${(x * 100).toFixed(2)}%`;
}

function ReturnCell({ value }: { value: number }) {
  const colour =
    value > 0
      ? "text-emerald-600 dark:text-emerald-400"
      : value < 0
      ? "text-red-500 dark:text-red-400"
      : "text-slate-500";
  return <span className={colour}>{pct(value)}</span>;
}

export default function Home() {
  const router = useRouter();
  const [data, setData] = useState<WatchlistData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [query, setQuery] = useState("");

  // Debounce by 300 ms — only used to decide when to show the lookup hint,
  // so we don't flash it on every keystroke.
  const debouncedQuery = useDebounce(query.trim().toUpperCase(), 300);

  useEffect(() => {
    fetch("/api/watchlist")
      .then((r) => {
        if (!r.ok) throw new Error(`Failed to load watchlist (${r.status})`);
        return r.json();
      })
      .then(setData)
      .catch((e) => setError(String(e)));
  }, []);

  const watchlist = data?.watchlist ?? [];

  // Filter watchlist rows as the user types (immediate, no debounce needed
  // for a local operation this cheap).
  const filtered = debouncedQuery
    ? watchlist.filter((r) => r.ticker.startsWith(debouncedQuery))
    : watchlist;

  const inWatchlist = watchlist.some((r) => r.ticker === debouncedQuery);
  const showLookupHint = debouncedQuery.length > 0 && !inWatchlist;

  function navigate() {
    if (debouncedQuery) router.push(`/ticker/${debouncedQuery}`);
  }

  function onKeyDown(e: KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Enter") navigate();
  }

  return (
    <main className="mx-auto max-w-4xl p-6 font-sans">
      <h1 className="mb-2 text-3xl font-bold tracking-tight">
        Equity Research Agent
      </h1>
      <p className="mb-6 max-w-2xl text-slate-600 dark:text-slate-400">
        Watchlist analytics generated by a Python pipeline — returns, drawdown,
        and volatility. Search any ticker to open its research pack.
      </p>

      {/* ── Search bar ── */}
      <div className="mb-4 flex max-w-sm gap-2">
        <input
          type="text"
          value={query}
          onChange={(e) => setQuery(e.target.value.toUpperCase())}
          onKeyDown={onKeyDown}
          placeholder="Search ticker…"
          maxLength={10}
          className="flex-1 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-mono
                     placeholder:text-slate-400 focus:border-indigo-500 focus:outline-none focus:ring-1
                     focus:ring-indigo-500 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-100"
        />
        <button
          onClick={navigate}
          disabled={!debouncedQuery}
          className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white
                     hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-40
                     dark:bg-indigo-500 dark:hover:bg-indigo-600"
        >
          Open →
        </button>
      </div>

      {/* Lookup hint — appears after debounce when symbol isn't in watchlist */}
      {showLookupHint && (
        <p className="mb-4 text-sm text-slate-500">
          <span className="font-mono font-semibold text-slate-700 dark:text-slate-300">
            {debouncedQuery}
          </span>{" "}
          is not in your watchlist — press ↵ to look it up anyway.
        </p>
      )}

      {!data && !error && <p className="text-slate-500">Loading watchlist…</p>}
      {error && <p className="text-red-500">Error: {error}</p>}

      {data && (
        <>
          <p className="mb-3 text-xs text-slate-400">
            Generated at: {new Date(data.generatedAt).toLocaleString()}
          </p>

          <div className="overflow-x-auto">
            <table className="w-full border-collapse text-sm">
              <thead>
                <tr className="border-b border-slate-200 dark:border-slate-700">
                  {["Ticker", "Last Close", "1Y Return", "Max Drawdown", "Ann. Vol"].map(
                    (h) => (
                      <th
                        key={h}
                        className="px-3 py-2.5 text-left font-medium text-slate-500 dark:text-slate-400"
                      >
                        {h}
                      </th>
                    )
                  )}
                </tr>
              </thead>
              <tbody>
                {filtered.length === 0 ? (
                  <tr>
                    <td
                      colSpan={5}
                      className="px-3 py-4 text-sm text-slate-400"
                    >
                      No watchlist match for &ldquo;{debouncedQuery}&rdquo;.
                    </td>
                  </tr>
                ) : (
                  filtered.map((row) => (
                    <tr
                      key={row.ticker}
                      className="border-b border-slate-100 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800/50"
                    >
                      <td className="px-3 py-2.5">
                        <a
                          href={`/ticker/${row.ticker}`}
                          className="font-mono font-semibold text-indigo-600 hover:underline dark:text-indigo-400"
                        >
                          {row.ticker}
                        </a>
                      </td>
                      <td className="px-3 py-2.5 tabular-nums">
                        ${row.lastClose.toFixed(2)}
                      </td>
                      <td className="px-3 py-2.5 tabular-nums">
                        <ReturnCell value={row.cumulativeReturn} />
                      </td>
                      <td className="px-3 py-2.5 tabular-nums">
                        <ReturnCell value={row.maxDrawdown} />
                      </td>
                      <td className="px-3 py-2.5 tabular-nums">
                        {pct(row.annualizedVolatility)}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>

          {data.correlationMatrix && (
            <CorrelationHeatmap matrix={data.correlationMatrix} />
          )}
        </>
      )}
    </main>
  );
}
